<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>자바스크립트예외처리except</title>
  </head>
  <body>
    <h1>자바스크립트예외처리except</h1>
    <p>프로그램의 실행을 중단시키는 요인을 에러 또는 예외라고 함</p>
    <p>
      error:개발자가 조치할 수 없는 시스템상의 오류 ex)네트워크오류, 전원차단의
      오류 except(예외);개발자가 조치할수 있는 문법오류 논리오류 실행오류
    </p>
    <p>자바스크립트의 요류는 try-catch문을 통해 관리가능</p>
    <p>try { 예외가 발생할만한 코드들 } catch(객체) { 예외처리코드 }</p>

    <script>
      document.write("-프로그램 시작-", "<br>");
      document.write(`100/10 = ${100 / 10}`, "<br>");
      document.write("-프로그램 끝-", "<br>");
      //정상실행 -시작 끝메시지 출력
    </script>
    <script>
      document.write("-프로그램 시작-", "<br>");
      document.write(`100/10 =${100 / num}`, "<br>"); //오류발생
      document.write("-프로그램 끝-", "<br>");
      //실행중단 -시작메시지만 출력
    </script>
    <script>
      //예외처리 1
      document.write("-프로그램 시작-", "<br>");
      try {
        document.write(`100/10 =${100 / num}`, "<br>");
      } catch (e) {
        document.write(`오류발생-num변수를 선언하고 <br>`);
      }
      document.write("-프로그램 끝-", "<br>");
    </script>
    <script>
      //예외처리 2
      try {
        document.write("-프로그램 시작-", "<br>");
        document.write(`100/10 = ${100 / num}`, "<br>");
        document.write("-프로그램 끝-", "<br>");
      } catch (e) {
        document.write(`오류발생 <br>`);
      }
    </script>

    <h2>오류 정보 확인</h2>
    <p>error객체의 name,message,stack 속성으로 확인 가능</p>

    <script>

        try {
            document.write("-프로그램 시작-", "<br>");
            document.write(`100/10 = ${100 / num}`, "<br>");
            document.write("-프로그램 끝-", "<br>");
        } catch (e) {
            document.write(e.name,'<br>');//오류 종류
            document.write(e.message,'<br>');//오류메세지
            document.write(e.stack,'<br>'); //오류발생 추적사항 ,발생위치 함수 알수 있다
        }
    </script>

  <h2>유형별 에외처리</h2>
  <p>오류 유형별로 메세지 처리를 상이하게 하고 싶으면 instanceof 연산자를 사용하면 됨</p>
  <p>referenceError:변수선언과 관련되 ㄴ오류</p>
  <p>rangeError:범위와 관련된</p>
  <p>syntaxError;문볍과 관련된</p>
  <p>typeError:변수나 객체의 자료형과 관련된</p>
  <script>
      try{
      document.write(sayhello);
      }catch (e){
        if  (e instanceof ReferenceError)
            //발생한 오류가 ReferenceError와 관련있는가?
            document.write(`오류:변수나 함수를 선언하세요`);
      }


  </script>
    <h2>인위적으로 오류발생시키기</h2>
    <p>특정 코드에 의해 발생되는 오류 외에도
        로직이 정상적으로 수행되는 특정조건을
        만족하지 못했을때 의도적으로 오류를 발생시켜
        catch 블럭에 의해 예외처리를 해야할 경우가 있음:</p>

    <p>이때 'throw 오류객체명' 구문으로
        오류를 발생시킬수 있음</p>

  <script>
      let checkAge = (age) =>{
          if(age <0 || age >= 100)
              document.write('나이를 올바르게 입력하세요');

      };
      let checkAge2= (age) =>{
          if(age <0 || age >= 100)
              throw new RangeError;
      };//나이의 범위가 벗어나면 인위적인 오류 발생

        try{
      checkAge2(150);
        }catch (e){
            if(e instanceof RangeError)
                document.write('나이를 올바르게 입력하세요');
        } //에외처리할때에는 이렇게만 쓴다만 알고 넘어간다 깊게 안나감
  </script>
  </body>
</html>
